exams/urls.py
from django.urls import path
from exams.views import ExamView,QuestionView,CheckAnswer,ExamResultView

app_name = "exam_app"

urlpatterns = [
    path('', ExamView.as_view(),name="exam"),
    path('question', QuestionView.as_view(),name="question"),
    path('check_answer', CheckAnswer.as_view(),name="check_answer"),
    path('create_exam', ExamResultView.as_view(),name="create_exam"),  
]

image_ai/urls.py
from django.urls import path
from .views import *
from . import consumers

app_name = 'imageai'

urlpatterns = [
    path('', IndexView.as_view(),name="home"),
    path('user_registration/', user_registration,name="user_registration"),
    path('save_image/', SavePicture.as_view(),name="save_image"),
    path('validate_image/', Validate_Image.as_view(),name="validate_image"),  
    path('face_identify/', FaceIdentificaton.as_view(),name="face_identify"),
]
# routing.py
# from django.urls import re_path


# websocket_urlpatterns = [
#     re_path(r'ws/camera/$', consumers.CameraConsumer.as_asgi()),
# ]

proctoring/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("image_ai.urls", namespace='image_ai')),
    path('screen_recorder_app/', include('screen_recorder.urls', namespace='screen_recorder_app')), 
    path('users/', include("users.urls", namespace='users')),
    path('exams/', include("exams.urls", namespace='exams')),    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include
from users.views import *
from . import views 
# from app import consumers
from django.urls import reverse

app_name = "users"

urlpatterns = [    
    path('login/', views.user_login, name="login"),
    path('register/', views.user_registration, name='register'),
    path('logout/', views.user_logout, name="logout"),    
]

templates/includes/_formhelpers.html
{% macro render_field(field) %}
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    {% for error in field.errors %}
	<div class="row justify-content-center">
            <div class="col-12 col-md-10">
                <div class="alert alert-danger shadow-soft" role="alert">
                   {{error}}
                </div>
            </div>
        </div>
    {% endfor %}
  {% endif %}
{% endmacro %}

templates/includes/_messages.html
<br><br><br>
<div class="alert" id="msg">{{msg}}</div>

  {% if messages %}
    {% for category, message in messages %}
	  <div class="row justify-content-center">
            <div class="col-12 col-md-10">
                <div class="alert alert-info shadow-soft" role="alert">
                    {{ message }}
                </div>
            </div>
        </div>
    {% endfor %}

  {% endif %}


{% if error %}
<div class="row justify-content-center">
            <div class="col-12 col-md-10">
                <div class="alert alert-danger shadow-soft" role="alert">
                   {{error}}
                </div>
            </div>
        </div>
{% endif %}

{% if msg %}
<div class="row justify-content-center">
            <div class="col-12 col-md-10">
                <div class="alert alert-success shadow-soft" role="alert">
                    {{msg}}
                </div>
            </div>
        </div>
{% endif %}

templates/includes/_navbar.html
{% load static %}
<script src="{% static 'assets/volt/vendor/sweetalert2/dist/sweetalert2.all.min.js' %}"></script>
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<header class="header-global">
   <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg navbar-theme-primary bg-white fixed-top"> 
<div class="container">
    <a class="navbar-brand" href="/"><span style="font-size:18px;"><center><lottie-player src="https://assets1.lottiefiles.com/packages/lf20_wEt2nn.json"  background="transparent"  speed="1"  style="width: 70px; height: 50px;"  loop  autoplay></lottie-player>CIS Proctor</center></span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">   
        <i class="fas fa-bars" style="color:#1c2540; font-size:28px;"></i>
    </span>
    </button>  
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="nav navbar-nav ml-auto">
      {% if not user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" id="active5" href="{% url 'users:login' %}"><span class="fas fa-user-plus" > Login</span></a></li>
      </li> 
      <li class="nav-item">
        <a class="nav-link" id="active5" href="{% url 'users:register' %}"><span class="fas fa-user-plus" > Register</span></a></li>
      </li>
      {% else %}
<!--       
      <li class="nav-item ">
        <a class="nav-link" id="active1" href="{% url 'image_ai:user_registration' %}"><span class="fas fa-user" > User Registration</span></a></li>
      </li> -->
      <li class="nav-item ">
        <a class="nav-link" id="active1" href="{% url 'exam_app:exam' %}"><span class="fas fa-columns" > Exam</span></a></li>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="active3" href="/contact"><span class="fas fa-phone-alt" > Contact Us</span></a></li>   
      </li>
      <li class="nav-item">
        <a class="nav-link" id="active7"  href="/faq"><span class="fas fa-question" > FAQ</span></a></li>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="active7"  href="{% url 'users:logout' %}"><span class="fas fa-user-plus" > Logout</span></a></li>
      </li> 
      {% endif %}  
	  </ul>
	</div>
	</div>
</nav>
</header>
<script>
    function funLogout () {
      swal.fire({
        title: 'Are you sure?',
        text: "Do you really want to logout?",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes, Logout me!',
        cancelButtonText: 'No!',
        confirmButtonColor: '#d33',
        cancelButtonColor: '#202124',
        reverseButtons: true
      }).then((result) => {
        if (result.isConfirmed) {
                    $.ajax({
                          type: "POST",
                          url: "/logout",
                          success: function(response){
                            if(response=="success")
                            {
                            console.log(response);
          window.location.href = "/";
                            }
      }
                      });  
            swal.fire(
            'Success!',
            'You are successfully has been sign out from the system.',
            'success'
          )
        } else if (
          result.dismiss === Swal.DismissReason.cancel
        ) {
          swal.fire(
            'Cancelled',
            'Logout cancelled.',
            'error'
          )
        }
      })
    }
</script>