exams/urls.py
from django.urls import path
from exams.views import ExamView,QuestionView,CheckAnswer,ExamResultView

app_name = "exam_app"

urlpatterns = [
    path('', ExamView.as_view(),name="exam"),
    path('question', QuestionView.as_view(),name="question"),
    path('check_answer', CheckAnswer.as_view(),name="check_answer"),
    path('create_exam', ExamResultView.as_view(),name="create_exam"),  
]

image_ai/urls.py
from django.urls import path
from .views import *
from . import consumers

app_name = 'imageai'

urlpatterns = [
    path('', IndexView.as_view(),name="home"),
    path('user_registration/', user_registration,name="user_registration"),
    path('save_image/', SavePicture.as_view(),name="save_image"),
    path('validate_image/', Validate_Image.as_view(),name="validate_image"),  
    path('face_identify/', FaceIdentificaton.as_view(),name="face_identify"),
]
# routing.py
# from django.urls import re_path


# websocket_urlpatterns = [
#     re_path(r'ws/camera/$', consumers.CameraConsumer.as_asgi()),
# ]

proctoring/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("image_ai.urls", namespace='image_ai')),
    path('screen_recorder_app/', include('screen_recorder.urls', namespace='screen_recorder_app')), 
    path('users/', include("users.urls", namespace='users')),
    path('exams/', include("exams.urls", namespace='exams')),    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include
from users.views import *
from . import views 
# from app import consumers
from django.urls import reverse

app_name = "users"

urlpatterns = [    
    path('login/', views.user_login, name="login"),
    path('register/', views.user_registration, name='register'),
    path('logout/', views.user_logout, name="logout"),    
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import JsonResponse


def user_login(request):
    if request.method == 'POST':  
        try:
            user = authenticate(username=request.POST['username'], password=request.POST['password'])        
            if user is not None:
                login(request,user)                     
                return JsonResponse({ 'status': 'success', 'message': 'You have successfully logged in.'})
            else:
                return JsonResponse({ 'status': 'error', 'message': 'Invalid credentials' })
        except User.DoesNotExist:
                return JsonResponse({ 'status': 'error', 'message': "User doesn't exist"})
    return render(request, 'users/login.html')



def user_registration(request):
    if request.method == 'POST':
        if request.POST.get('email'):
            if User.objects.filter(email = request.POST.get('email')).exists():
                return JsonResponse({ 'status': 'error', 'message': 'User already exists with the given email. Try another' })
            else:
                user = User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
                user.first_name = request.POST['firstname']
                user.last_name = request.POST['lastname']        
                user.save()
                return JsonResponse({ 'status' : 'success', 'message':'Registration successful. Please login using your credentials' })     
    return render(request, 'users/register.html')



def user_logout(request):
    logout(request)
    return redirect ('users:login')

templates/users/login.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
 <main>
 <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
  <div class="container">
    <div class="col-12 d-flex align-items-center justify-content-center">
      <div class="bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-650">
        <div class="text-center text-md-center mb-4 mt-md-0">
          <h1 class="mb-0 h3">Sign in to our platform</h1>
        </div>
        <img src="{% static 'assets/secure_login.png' %}">
        <div class="card-body">
          <form name='login_form' method="post" class="mt-4">
            {% csrf_token %}
            <div class="form-group">
              <label for="email">Username</label>
              <div class="input-group mb-4">
                <div class="input-group-prepend">
                  <span class="input-group-text"><span class="fas fa-envelope"></span></span>
                </div>
                <input name="username" class="form-control" id="login-username" placeholder="Joe" type="text" required>
              </div>
            </div>

            <div class="form-group">
              <div class="form-group">
                <label for="password">Password</label>
                <div class="input-group mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><span class="fas fa-unlock-alt"></span></span>
                  </div>
                  <input name="password" type="text" id="login-password" class="form-control" placeholder="Password"
                    style="-webkit-text-security:disc;" aria-label="Password" required>
                </div>
              </div>
            </div>

            <!-- <div class="form-group">
                                        <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Choose User Type</label>
                                        <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref" name="user_type" required>
                                            <option value="student">Student</option>
                                            <option value="teacher">Professor</option>
                                        </select>
                                    </div> -->

            <!-- <div class="form-group">
                                        <video id="stream" width="370" height="320">
                                            <canvas id="capture" width="370" height="320">
                                            </canvas>
                                          </video>
                                            <button id="btn-capture" type="button" class="btn btn-primary justify-content-center">Capture Image</button>
                                        <br><br>
                                            <div id="snapshot"></div>
                                        <input type="hidden" id="image_hidden" name="image_hidden">
                                        </div> -->

            <div class="d-flex justify-content-between align-items-center mb-4">
              <div><a href="/lostpassword" class="font-weight-bold">Lost password?</a></div>
            </div>
            <input type="hidden" name="form_name" value="login_form">
            <button type="submit" id="login-btn" class="btn btn-block btn-primary">Sign in</button>
          </form>

          <div class="d-block d-sm-flex justify-content-center align-items-center mt-4">
            <span class="font-weight-normal">
              Not registered?
              <a href="{% url 'users:register' %}" class="font-weight-bold">Create account</a>
            </span>
          </div>
        </div>
      </div>
      <div>
      </div>
    </div>
</section>
</main>
<script>

$('#login-btn').click(function(e){
        e.preventDefault();

        let username = $('#login-username').val()
        let password = $('#login-password').val()
        let csrf = $('input[name=csrfmiddlewaretoken]').val()

        if (!username || !password){
            Notiflix.Notify.failure('Required credentials must be filled properly')
        } else {
            datatosend = { username: username, password: password, csrfmiddlewaretoken: csrf }

            $.ajax({
                url : "{% url 'users:login' %}",
                method: "POST",
                data: datatosend,
                success: function(response) {
                    if(response.status == 'success'){
                        Notiflix.Notify.success(response.message)
                        setTimeout(function(){
                        location.href = "{% url 'imageai:user_registration' %}";
                        },2000);
                    } else {
                        Notiflix.Notify.failure(response.message);
                    }
                }
            })
        }  
    })

  var btnCapture = document.getElementById("btn-capture");
  var stream = document.getElementById("stream");
  var capture = document.getElementById("capture");
  var snapshot = document.getElementById("snapshot");
  var cameraStream = null;

  btnCapture.addEventListener("click", captureSnapshot);

  function startStreaming() {

    var mediaSupport = 'mediaDevices' in navigator;

    if (mediaSupport && null == cameraStream) {

      navigator.mediaDevices.getUserMedia({ video: true })
        .then(function (mediaStream) {
          cameraStream = mediaStream;
          stream.srcObject = mediaStream;
          stream.play();
        })
        .catch(function (err) {
          console.log("Unable to access camera: " + err);
        });
    }
    else {
      alert('Your browser does not support media devices.');
      return;
    }
  }

  function stopStreaming() {
    if (null != cameraStream) {
      var track = cameraStream.getTracks()[0];
      track.stop();
      stream.load();
      cameraStream = null;
    }
  }

  function captureSnapshot() {
    if (null != cameraStream) {
      var ctx = capture.getContext('2d');
      var img = new Image();
      ctx.drawImage(stream, 0, 0, capture.width, capture.height);
      img.src = capture.toDataURL("image/png");
      img.width = 370;
      img.height = 320;
      //console.log(capture.toDataURL( "image/png" ));
      snapshot.innerHTML = '';
      snapshot.appendChild(img);
      var d1 = capture.toDataURL("image/png");
      var res = d1.replace("data:image/png;base64,", "");
      console.log(res);
      snapshot.innerHTML = '';
      snapshot.appendChild(img);
      $("#image_hidden").val(res)
    }
  }
  window.onload = function () {
    startStreaming();
    captureSnapshot();
  }


  
</script>
{% endblock %}

templates/users/register.html
{% extends 'layout.html' %}
{% block body %}
{% load static %}
<main>
  <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
    <div class="container">
      <div class="col-12 d-flex align-items-center justify-content-center">
        <div class="bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-650">
          <div class="text-center text-md-center mb-4 mt-md-0">
            <h1 class="mb-0 h3">Create an Account</h1>
          </div>
          <img src="{% static 'assets/personal_information.png' %}" style="position: relative;max-width: 30%;left: 35%;">
          <div class="card-body">
            <form name='register_form' method="post" action="{% url 'users:register'%}" class="mt-4">
              {% csrf_token %}
              <div class="form-group">
                <label for="firstname">FIRSTNAME</label>
                <div class="input-group mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><span class="fas fa-user"></span></span>
                  </div>
                  <input name="firstname" type="text" class="form-control" id="firstname" placeholder="Joe"
                    aria-label="firstname" required>
                </div>
              </div>
              <div class="form-group">
                <label for="lastname">LASTNAME</label>
                <div class="input-group mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><span class="fas fa-user"></span></span>
                  </div>
                  <input name="lastname" type="text" class="form-control" id="lastname" placeholder="Doe"
                    aria-label="lastname" required>
                </div>
              </div>
              <div class="form-group">
                <label for="username">USERNAME</label>
                <div class="input-group mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><span class="fas fa-user"></span></span>
                  </div>
                  <input name="username" class="form-control" id="username" placeholder="JohnDoe" type="text" required>
                </div>
              </div>
              <div class="form-group">
                <label for="email">EMAIL</label>
                <div class="input-group mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><span class="fas fa-envelope"></span></span>
                  </div>
                  <input name="email" class="form-control" id="email" placeholder="johndie@example.com" type="email" required>
                </div>
              </div>
              <div class="form-group">
                <label for="password">PASSWORD</label>
                <div class="input-group mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><span class="fas fa-unlock-alt"></span></span>
                  </div>
                  <input name="password" type="text" class="form-control" id="password"
                    style="-webkit-text-security:disc;" placeholder="Password" aria-label="Password" required>
                </div>
              </div>
              <input type="hidden" name="form_name" value="register_form">
              <input type="submit" class="btn btn-primary form-group justify-content-center" id="register-btn" value="Register">
            </form>
            <p>Already have an account?
              <a href="{% url 'users:login' %}">Click here</a>.
            </p>
          </div>
          <div>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
    </div>
  </section>
  <div class="modal fade" id="CameraModal" tabindex="-1" aria-labelledby="cameraModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header" style="display: flex; flex-direction: column;">
          <h5 class="modal-title" id="cameraModalLabel">Hello, we need to take a picture</h5>
          <div style="display: flex; flex-direction: column;font-size: small;color: darkgrey;">
            <span>Please sit straight.</span>
            <span>Align yourself in the center of the frame.</span>
            <span>Ensure your background is plain.</span>
          </div>          

          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="margin-top: -40px;"></button>
        </div>
        <div class="modal-body">
          <div class="container" >
            <video id="cameraFeed" preload="auto" autoplay style="width: 100%; height: auto;"></video>
            <canvas id="photoCanvas" style="display: none; "></canvas>
            <img id="capturedPhoto" style="display: none;margin-bottom:10px;width: 100%; height: auto;">
          </div>
          <button type="button" id="retakePicture" style="display: none;" class="btn btn-primary">Retake</button>
          <button type="button" id="takePicture" class="btn btn-primary">Take my picture</button>
       

          <button type="button" id="savePicture" style="display: none;" class="btn btn-primary">Save</button>
          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        </div>        
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="CameraModal" tabindex="-1" aria-labelledby="cameraModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header" style="display: flex; flex-direction: column;">
          <h5 class="modal-title" id="cameraModalLabel">Hello, we need to take a picture</h5>
          <div style="display: flex; flex-direction: column;font-size: small;color: darkgrey;">
            <span>Please sit straight.</span>
            <span>Align yourself in the center of the frame.</span>
            <span>Ensure your background is plain.</span>
          </div>          

          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="margin-top: -40px;"></button>
        </div>
        <div class="modal-body">
          <div class="container" >
            <video id="cameraFeed" preload="auto" autoplay style="width: 100%; height: auto;"></video>
            <canvas id="photoCanvas" style="display: none; "></canvas>
            <img id="capturedPhoto" style="display: none;margin-bottom:10px;width: 100%; height: auto;">
          </div>
          <button type="button" id="retakePicture" style="display: none;" class="btn btn-primary">Retake</button>
          <button type="button" id="takePicture" class="btn btn-primary">Take my picture</button>
       

          <button type="button" id="savePicture" style="display: none;" class="btn btn-primary">Save</button>
          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        </div>        
      </div>
    </div>
  </div>
</main>
<script>

  $(document).ready(function () {
    function dataURLtoBlob(dataURL) {
      var arr = dataURL.split(',');
      var mime = arr[0].match(/:(.*?);/)[1];
      var bstr = atob(arr[1]);
      var n = bstr.length;
      var u8arr = new Uint8Array(n);

      while (n--) {
        u8arr[n] = bstr.charCodeAt(n);
      }

      return new Blob([u8arr], { type: mime });
    }

    var imageData;
    var video = document.getElementById('cameraFeed');
    var canvas = document.getElementById('photoCanvas');
    var photo = document.getElementById('capturedPhoto');
    var save = document.getElementById('savePicture');
    var retake = document.getElementById('retakePicture');
    var takePicture = document.getElementById('takePicture');


    $('#CameraModal').on('shown.bs.modal', function () {
      if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
        navigator.mediaDevices.getUserMedia({ video: true })
          .then(function (stream) {
            var video = document.getElementById('cameraFeed');
            video.srcObject = stream;

          })
          .catch(function (error) {
            console.error('Error accessing webcam: ', error);
          });
      }
    });

    $('#takePicture').click(function () {

      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);

      photo.src = canvas.toDataURL('image/png');
      var csrfToken = $('[name=csrfmiddlewaretoken]').val();
      var blob = dataURLtoBlob(canvas.toDataURL('image/png'));
      var formData = new FormData();
      formData.append("file", blob);
      $.ajax({
        url: '/validate_image/',
        type: "POST",
        data: {
          image_data: canvas.toDataURL('image/png'),
          csrfmiddlewaretoken: csrfToken,
        },

        success: function (response) {
          console.log(response['message']);
          if (!response['message']) {
            video.style.display = 'none';
            photo.style.display = 'block';
            imageData = canvas.toDataURL('image/png');
            takePicture.style.display = 'none';
            save.style.display = 'inline';
            retake.style.display = 'inline';
          }
          else {
            Notiflix.Notify.failure(response['message']);

          }

        },
        error: function (error) {
          console.error('Error saving the image:', error);

        }
      });

    });

    $('#savePicture').click(function () {
      var csrfToken = $('[name=csrfmiddlewaretoken]').val();
      $.ajax({
        type: 'POST',
        url: '/save_image/',
        data: {
          image_data: imageData,
          user: "{{user.id}}",
          csrfmiddlewaretoken: csrfToken,
        },
        success: function (response) {
          var takemypicbtn = document.getElementById('takemypicbtn');

          console.log('Image saved to the server.');
          $('#CameraModal').modal('hide');
          $('.modal-backdrop').hide()
          takemypicbtn.style.display = 'none';

          $("#question").append(`<button type="button" class="btn btn-primary rounded" disabled>Verified</button>`)

        },
        error: function (error) {
          console.error('Error saving the image:', error);
        }
      });
    });



    $("#retakePicture").click(function () {

      video.style.display = 'block';
      photo.style.display = 'none';
      takePicture.style.display = 'inline';
      save.style.display = 'none';
      retake.style.display = 'none';
      $(".container").css("margin-bottom", "10px");


    })


    $('#register-btn').click(function(e){
        e.preventDefault();

        let username = $('#username').val()
        let password = $('#password').val()
        let firstname = $('#firstname').val()
        let lastname = $('#lastname').val()
        let email = $('#email').val()
        let csrf = $('input[name=csrfmiddlewaretoken]').val()

        if (!username || !password || !email){
            Notiflix.Notify.failure("Required credentials should be filled properly")
        } else {
            datatosend = { username: username, firstname: firstname, lastname: lastname, email: email, password: password,csrfmiddlewaretoken: csrf  }

            $.ajax({
                url: "{% url 'users:register' %}",
                method: "POST",
                data: datatosend,
                success: function(response){
                    if (response.status == 'success') {
                        Notiflix.Notify.success(response.message)
                        setTimeout(function(){
                        location.href = "{% url 'users:login' %}";
                        },2000);
                    } else {
                        Notiflix.Notify.failure(response.message)
                    }
                }
            })
        }

        
    })


  });



</script>
<script src='{% static "js/jquery.min.js"%}'></script>
<script src='{% static "js/popper.js"%}'></script>
<script src='{% static "js/bootstrap.min.js"%}'></script>
<script src='{% static "js/main.js"%}'></script>
<script src='{% static "js/notiflix-aio-3.2.6.min.js" %}'></script>
<script src="https://cdn.webrtc-experiment.com/RecordRTC.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% endblock %}